touch ./build/split/2.csv
touch ./build/split/3.csv
touch ./build/split/4.csv
touch ./build/split/5.csv
touch ./build/split/6.csv
touch ./build/split/7.csv
touch ./build/split/8.csv
touch ./build/split/9.csv
touch ./build/split/10.csv
touch ./build/split/11.csv
touch ./build/split/12.csv
touch ./build/split/13.csv
touch ./build/split/14.csv
touch ./build/split/15.csv
touch ./build/split/16.csv
touch ./build/split/17.csv
touch ./build/split/18.csv
